CREATE TABLE legends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_legends_name UNIQUE (name)
);

CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_players_name UNIQUE (name)
);

CREATE TABLE decks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    legend_id BIGINT NOT NULL,
    CONSTRAINT fk_decks_legend FOREIGN KEY (legend_id) REFERENCES legends (id)
);

CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    played_at TIMESTAMP NOT NULL,
    opponent_id BIGINT NOT NULL,
    my_deck_id BIGINT NOT NULL,
    opponent_deck_id BIGINT NOT NULL,
    result VARCHAR(10) NOT NULL,
    my_final_score INT NOT NULL,
    opponent_final_score INT NOT NULL,
    CONSTRAINT fk_matches_opponent FOREIGN KEY (opponent_id) REFERENCES players (id),
    CONSTRAINT fk_matches_my_deck FOREIGN KEY (my_deck_id) REFERENCES decks (id),
    CONSTRAINT fk_matches_opponent_deck FOREIGN KEY (opponent_deck_id) REFERENCES decks (id)
);

CREATE TABLE match_rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    round_number INT NOT NULL,
    my_score INT NOT NULL,
    opponent_score INT NOT NULL,
    CONSTRAINT fk_match_rounds_match FOREIGN KEY (match_id) REFERENCES matches (id)
);
